---
- name: restart new relic
  service:
    name: newrelic-sysmond
    state: restarted

- name: run new relic installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - restart php-fpm
    - restart nginx

- name: restart php-fpm
  shell: service php7.0-fpm restart

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

