---
- name: Create sftp user group
  group: name=filetransfer state=present

- name: Create sftp default user
  user: name=wordpress-sftp groups=filetransfer state=present home=/home/wordpress-sftp

- name: Create home directory
  file: path=/home/wordpress-sftp owner=root group=root mode=755

- name: Creates directory for ssh keys
  file: path=/home/wordpress-sftp/.ssh state=directory owner=wordpress-sftp group=wordpress-sftp mode=700

- name: Creates authorized_keys file
  file: path=/home/wordpress-sftp/.ssh/authorized_keys owner=wordpress-sftp group=wordpress-sftp mode=600 state=touch

- name: Copy sshd_config template
  template: src=sshd_config dest=/etc/ssh/ force=yes
  notify: restart sshd

- name: Create html directory
  file: path=/home/wordpress-sftp/html owner=wordpress-sftp group=wordpress-sftp state=directory

- name: Mount html directory
  mount: opts=bind fstype=none state=mounted name=/var/www/html/wordpress src=/home/wordpress-sftp/html